### ISSUE TITLE
Bestellung anzeigen in neuem Tab nervt

### ISSUE THREAD

**Issue by angelaboehm** [dominikbraun/foodunit#14]
Änder das!

**Comment by alinnert** [comment]
Agree. Wenn man das möchte, kann man das per mittlerer Maustaste oder `strg` + `Klick` selbst machen. Ich find sowas nur für externe Links aus Anwendungen heraus sinnvoll, oder wenn man verhindern möchte, dass ein halbfertiges Formular durch eine Navigation gelöscht werden würde.

tl;dr: bitte fixen!!!!!11!1 xD

**Comment by dominikbraun** [comment]
Ihr Penner!

Done.

**Comment by alinnert** [comment]
Ich find's ja lustig, weil ich auf GitHub bisher nur englische und ernsthafte Kommunikation gewohnt bin :'D

**Comment by dominikbraun** [comment]
> weil ich auf GitHub bisher nur englische und ernsthafte Kommunikation gewohnt bin :'D

Ich auch, aber da haben wir die Rechnung ohne Ablont gemacht.
