### ISSUE TITLE
Login anfordern bestätigen

### ISSUE THREAD

**Issue by angelaboehm** [dominikbraun/foodunit#17]
Eine Antwort wie "Eine E-Mail wurder verschickt" wär hilfreich, da man sonst nicht weiß ob es geklappt hat und was als nächstes passiert

**Comment by dominikbraun** [comment]
Das wurde mal gefixt: https://github.com/dominikbraun/foodunit/issues/3

**Comment by dominikbraun** [comment]
https://github.com/dominikbraun/foodunit/commit/cd296e94c934577dac457c6e7545e07d60a3739b
