### ISSUE TITLE
Speisekarten-Liste

### ISSUE THREAD

**Issue by Ablont** [dominikbraun/foodunit#20]
Eine Liste aller gepflegten Speisekarten unabhängig vom aktuell ausgewählten Restaurant

**Comment by dominikbraun** [comment]
Sollen dann die entsprechenden Gerichte auch auswählbar (=bestellbar) sein? In der Hoffnung, dass es jemand abholt? :D

**Comment by dominikbraun** [comment]
Die Möglichkeit, mehrere Speisekarten (Restaurants) anzubieten, wurde mit FU 2 umgesetzt. Sobald der Wunsch nach parallelen Bestellungen aufkommt, wird's eben ins Frontend übernommen.
