### ISSUE TITLE
Gruppen-Krabbeln

### ISSUE THREAD

**Issue by alinnert** [dominikbraun/foodunit#25]
Nach einer Runde Gruppen-Krabbeln hätt ich Hunger auf eine große Krabbel-Pizza mit **Extra-Krabbeln** und eine Tüte Krabbel-Chips. Weißte bescheid. 😁

**Comment by dominikbraun** [comment]
Ich denke, ich weiß, was gemeint ist. :D

**Comment by dominikbraun** [comment]
Done
