### ISSUE TITLE
Layout komplett zerschossen! Bitte fixen!!!!11elf 😱

### ISSUE THREAD

**Issue by alinnert** [dominikbraun/foodunit#29]
![food-unit-responsive](https://user-images.githubusercontent.com/2638971/58537070-6189cb80-81f2-11e9-95d2-a3bcde47d2c1.png)

Wenn man das Fenster kleiner macht, schiebt sich die Bestellübersicht rechts ausm Viewport.

Ganz wichtiger Bug!
Priorität: 💯³

**Comment by dominikbraun** [comment]
Wurde bereits mit FU 2 behoben. 😎
