### ISSUE TITLE
Datum der Bestellrunde anzeigen

### ISSUE THREAD

**Issue by alinnert** [dominikbraun/foodunit#32]
Wär manchmal hilfreich zu sehen, für welches Datum eine Bestellrunde gilt. Nicht dass es sich um eine Alte handelt (z. B. von gestern oder letzter Woche), ich da eine Bestellung abgebe und ich dann verhungern muss 😢

**Comment by dominikbraun** [comment]
Wird aufgrund des neuen Konzepts von Bestellrunden in FU 3 umgesetzt.
