### ISSUE TITLE
Repo-Beschreibung englisch -> deutsch?

### ISSUE THREAD

**Issue by alinnert** [dominikbraun/foodunit#33]
Glaub die Repo-Beschreibung (ganz oben auf der Seite) ist das einzige, das hier noch englisch ist. Wär hier deutsch nicht sinnvoller, damit es einheitlich zum Rest ist?

**Comment by dominikbraun** [comment]
Die Beschreibungen von v2 bleiben auf Deutsch erhalten, alle zukünftigen Beschreibungen werd ich auf Englisch schreiben (auch Commits).

**Comment by alinnert** [comment]
Kriegt FoodUnit dann eine richtig nice Lokalisierung? 😄

**Comment by dominikbraun** [comment]
Ja, das übernimmt dann der gute @alinnert im Frontend :)

**Comment by alinnert** [comment]
Ach der. Ja, der kann das 😆
