### ISSUE TITLE
Warenkorb mitscrollen lassen

### ISSUE THREAD

**Issue by dominikbraun** [dominikbraun/foodunit#4]
Um die aktuellen Positionen im Warenkorb mitverfolgen zu können, müsste er mit nach unten scrollen.

**Comment by Ablont** [comment]
Zusätzlich den Preis pro Artikel im Warenkorb anzeigen

**Comment by dominikbraun** [comment]
> Zusätzlich den Preis pro Artikel im Warenkorb anzeigen

Hab ich gesondert angelegt. https://github.com/dominikbraun/foodunit/issues/7

**Comment by dominikbraun** [comment]
Done.
