### ISSUE TITLE
"Oder"-Angaben für Produkte

### ISSUE THREAD

**Issue by Ablont** [dominikbraun/foodunit#6]
Optimal wäre es, wenn es für "oder"-Angaben eines Artikels eine Auswahl zur Selektion gäbe.
Dann muss das nicht immer in die Zeile für Zusatz schreiben.

Beispiel: "... und Pommes oder Reis".

**Comment by dominikbraun** [comment]
Viel Arbeit, wenig Zugewinn. Vielleicht kommen Variantenkonfigurationen mit FoodUnit 3?
