### ISSUE TITLE
Preise der Positionen im Warenkorb anzeigen

### ISSUE THREAD

**Issue by dominikbraun** [dominikbraun/foodunit#7]
Der Preis einer einzelnen Position sollte im Warenkorb angezeigt werden, um die Einzelpreise besser ersichtlich zu machen.

**Comment by angelaboehm** [comment]
Bestellung anzeigen im neuen Tab nervt. Änder das!

**Comment by dominikbraun** [comment]
https://github.com/dominikbraun/foodunit/commit/b9f23c264894ac0af04c596106ecef5c4b408b06
